# .github/workflows/preview.yml
name: Commit Previews to "pages" branch
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pull-requests: write


jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      # - run: npm i && npm run build
      - name: npm
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Angular CLI
        if: github.event.action != 'closed'
        run: npm install -g @angular/cli
        working-directory: ./frontend

      - name: Install dependencies  
        if: github.event.action != 'closed'
        run: npm ci
        working-directory: ./frontend

      - name: Build Angular Project | Use Node.js ${{ matrix.node-version }}
        if: github.event.action != 'closed'
        # base-href is set to the PR number. exact style here https://github.com/marketplace/actions/deploy-pr-preview
        run: ng build --output-path ./docs --base-href https://ar-kareem.github.io/PythonDiceWeb/pr-preview/pr-${{ github.event.number }}/
        working-directory: ./frontend


      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./frontend/docs/browser/
          preview-branch: pages
          umbrella-dir: pr-preview
          action: auto
